import type { NamedLocation } from '../scene/Scene.ts';

export interface SceneTilemapData {
  floor: string[][];
  decor: string[][];
  walkable: boolean[][];
  locations: Record<string, NamedLocation>;
}

export const SCENE_TILEMAPS: Record<'huanglong' | 'blackshores' | 'rinascita' | 'frontier', SceneTilemapData> = {
  huanglong: {
    floor: [
      ['wall_green', 'wall_green', 'wall_green', 'wall_green', 'wall_green', 'wall_green', 'wall_green', 'wall_green', 'wall_green', 'wall_green', 'wall_green', 'wall_green', 'wall_green', 'wall_green', 'wall_green', 'wall_green'],
      ['wall_green', 'floor_resonance', 'floor_resonance', 'floor_resonance', 'floor_resonance', 'floor_resonance', 'floor_resonance', 'floor_resonance', 'floor_resonance', 'floor_resonance', 'floor_resonance', 'floor_resonance', 'floor_resonance', 'floor_resonance', 'floor_resonance', 'wall_green'],
      ['wall_green', 'floor_resonance', 'floor_resonance', 'floor_resonance', 'floor_resonance', 'floor_resonance', 'floor_resonance', 'floor_resonance', 'floor_resonance', 'floor_resonance', 'floor_resonance', 'floor_resonance', 'floor_resonance', 'floor_resonance', 'floor_resonance', 'wall_green'],
      ['wall_green', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor', 'floor', 'floor', 'floor', 'floor', 'floor_green', 'floor_green', 'floor_green', 'floor_green', 'floor_green', 'wall_green'],
      ['wall_green', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor', 'floor', 'floor', 'floor', 'floor', 'floor_green', 'floor_green', 'floor_green', 'floor_green', 'floor_green', 'wall_green'],
      ['wall_green', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor', 'floor', 'floor', 'floor', 'floor', 'floor_green', 'floor_green', 'floor_green', 'floor_green', 'floor_green', 'wall_green'],
      ['wall_green', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor', 'floor', 'floor', 'floor', 'floor', 'floor_green', 'floor_green', 'floor_green', 'floor_green', 'floor_green', 'wall_green'],
      ['wall_green', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor', 'floor', 'floor', 'floor', 'floor', 'floor_green', 'floor_green', 'floor_green', 'floor_green', 'floor_green', 'wall_green'],
      ['wall_green', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'wall_green'],
      ['wall_green', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'wall_green'],
      ['wall_green', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'wall_green'],
      ['wall_green', 'wall_green', 'wall_green', 'wall_green', 'wall_green', 'wall_green', 'wall_green', 'wall_green', 'wall_green', 'wall_green', 'wall_green', 'wall_green', 'wall_green', 'wall_green', 'wall_green', 'wall_green'],
    ],
    decor: [
      ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
      ['', '', 'window', 'window', '', '', '', '', '', '', 'bookshelf', 'bookshelf', 'plant', 'papers', '', ''],
      ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
      ['', '', 'console', 'plant', '', 'desk', 'chair', 'rug', 'bookshelf', 'lamp', 'board', 'papers', 'shelf', 'lamp', '', ''],
      ['', '', 'monitor', '', '', '', '', '', '', '', '', '', '', '', '', ''],
      ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
      ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
      ['', '', '', '', 'table', 'chair', 'chair', 'plant', 'rug', '', '', 'divider', 'window', 'plant', '', ''],
      ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
      ['', '', '', 'couch', 'table', 'lamp', 'papers', '', '', '', 'bench', 'plant', '', '', '', ''],
      ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
      ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
    ],
    walkable: [
      [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      [false, true, true, true, true, true, true, true, true, true, false, false, false, false, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, true, false, false, true, false, false, false, false, false, false, false, false, false, true, false],
      [false, true, false, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, true, true, true, false, false, false, false, false, true, true, false, false, false, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, true, true, false, false, false, false, true, true, true, false, false, true, true, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    ],
    locations: {
      huanglong_city_console: { x: 2, y: 4, label: '今州中控台' },
      huanglong_city_center: { x: 8, y: 5, label: '今州城主街' },
      huanglong_strategy_map: { x: 10, y: 3, label: '虹镇调度图' },
      huanglong_rainbow_town: { x: 12, y: 5, label: '虹镇驿桥' },
      huanglong_peach_garden: { x: 2, y: 8, label: '桃源乡庭院' },
      huanglong_cloud_peak: { x: 12, y: 9, label: '乘霄山观景台' },
      huanglong_city_walk_1: { x: 6, y: 6, label: '云桥 A' },
      huanglong_city_walk_2: { x: 9, y: 8, label: '云桥 B' },
    },
  },
  blackshores: {
    floor: [
      ['wall_purple', 'wall_purple', 'wall_purple', 'wall_purple', 'wall_purple', 'wall_purple', 'wall_purple', 'wall_purple', 'wall_purple', 'wall_purple', 'wall_purple', 'wall_purple', 'wall_purple', 'wall_purple', 'wall_purple', 'wall_purple'],
      ['wall_purple', 'floor_grid', 'floor_grid', 'floor_grid', 'floor_grid', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_purple', 'floor_purple', 'floor_purple', 'floor_purple', 'wall_purple'],
      ['wall_purple', 'floor_grid', 'floor_grid', 'floor_grid', 'floor_grid', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_grid', 'floor_grid', 'floor_grid', 'floor_grid', 'wall_purple'],
      ['wall_purple', 'floor_grid', 'floor_grid', 'floor_grid', 'floor_grid', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_grid', 'floor_grid', 'floor_grid', 'floor_grid', 'wall_purple'],
      ['wall_purple', 'floor_purple', 'floor_purple', 'floor_purple', 'floor_purple', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_purple', 'floor_purple', 'floor_purple', 'floor_purple', 'wall_purple'],
      ['wall_purple', 'floor_purple', 'floor_purple', 'floor_purple', 'floor_purple', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_purple', 'floor_purple', 'floor_purple', 'floor_purple', 'wall_purple'],
      ['wall_purple', 'floor_purple', 'floor_purple', 'floor_purple', 'floor_purple', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_purple', 'floor_purple', 'floor_purple', 'floor_purple', 'wall_purple'],
      ['wall_purple', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'wall_purple'],
      ['wall_purple', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'wall_purple'],
      ['wall_purple', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'wall_purple'],
      ['wall_purple', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_ring', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'wall_purple'],
      ['wall_purple', 'wall_purple', 'wall_purple', 'wall_purple', 'wall_purple', 'wall_purple', 'wall_purple', 'wall_purple', 'wall_purple', 'wall_purple', 'wall_purple', 'wall_purple', 'wall_purple', 'wall_purple', 'wall_purple', 'wall_purple'],
    ],
    decor: [
      ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
      ['', '', 'window', '', '', '', '', '', '', '', '', '', '', 'window', '', ''],
      ['', '', '', '', 'console', 'monitor', 'desk', 'chair', '', '', 'archive', 'bookshelf', 'plant', 'papers', '', ''],
      ['', '', '', '', '', '', '', 'holo', 'lamp', 'plant', 'rug', '', '', '', '', ''],
      ['', '', '', '', '', '', '', '', '', '', '', 'board', 'divider', '', '', ''],
      ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
      ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
      ['', '', '', 'pod', '', '', '', '', '', '', '', '', '', '', '', ''],
      ['', '', '', '', 'pod', '', 'couch', 'table', 'chair', 'papers', 'plant', 'rug', 'couch', 'plant', '', ''],
      ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
      ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
      ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
    ],
    walkable: [
      [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      [false, true, false, true, true, true, true, true, true, true, true, true, true, false, true, false],
      [false, true, true, true, false, false, false, false, true, true, false, false, false, false, true, false],
      [false, true, true, true, true, true, true, false, false, false, false, true, true, true, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, false, false, true, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, true, true, false, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, true, true, true, false, true, false, false, false, false, false, false, false, false, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    ],
    locations: {
      blackshores_command_desk: { x: 4, y: 4, label: '黑海岸指挥席' },
      blackshores_tethys_core: { x: 8, y: 5, label: '泰缇斯之底' },
      blackshores_data_wall: { x: 11, y: 5, label: '潮汐数据墙' },
      blackshores_vault: { x: 10, y: 3, label: '金库封存区' },
      blackshores_garden: { x: 12, y: 9, label: '花房露台' },
      blackshores_center: { x: 8, y: 7, label: '潮汐甲板' },
      blackshores_walk_1: { x: 6, y: 5, label: '廊桥 A' },
      blackshores_walk_2: { x: 10, y: 8, label: '廊桥 B' },
    },
  },
  rinascita: {
    floor: [
      ['wall_warm', 'wall_warm', 'wall_warm', 'wall_warm', 'wall_warm', 'wall_warm', 'wall_warm', 'wall_warm', 'wall_warm', 'wall_warm', 'wall_warm', 'wall_warm', 'wall_warm', 'wall_warm', 'wall_warm', 'wall_warm'],
      ['wall_warm', 'floor_warm', 'floor_warm', 'floor_warm', 'floor_warm', 'floor_warm', 'floor_warm', 'floor_warm', 'floor_warm', 'floor_warm', 'floor_tile_warm', 'floor_tile_warm', 'floor_tile_warm', 'floor_tile_warm', 'floor_tile_warm', 'wall_warm'],
      ['wall_warm', 'floor_warm', 'floor_warm', 'floor_warm', 'floor_warm', 'floor_warm', 'floor_warm', 'floor_warm', 'floor_warm', 'floor_warm', 'floor_tile_warm', 'floor_tile_warm', 'floor_tile_warm', 'floor_tile_warm', 'floor_tile_warm', 'wall_warm'],
      ['wall_warm', 'floor_warm', 'floor_warm', 'floor_warm', 'floor_warm', 'floor_warm', 'floor_warm', 'floor_warm', 'floor_warm', 'floor_warm', 'floor_tile_warm', 'floor_tile_warm', 'floor_tile_warm', 'floor_tile_warm', 'floor_tile_warm', 'wall_warm'],
      ['wall_warm', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_warm', 'floor_warm', 'floor_warm', 'floor_warm', 'floor_warm', 'floor_tile_warm', 'floor_tile_warm', 'floor_tile_warm', 'floor_tile_warm', 'floor_tile_warm', 'wall_warm'],
      ['wall_warm', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_warm', 'floor_warm', 'floor_warm', 'floor_warm', 'floor_warm', 'floor_tile_warm', 'floor_tile_warm', 'floor_tile_warm', 'floor_tile_warm', 'floor_tile_warm', 'wall_warm'],
      ['wall_warm', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_warm', 'floor_warm', 'floor_warm', 'floor_warm', 'floor_warm', 'floor_tile_warm', 'floor_tile_warm', 'floor_tile_warm', 'floor_tile_warm', 'floor_tile_warm', 'wall_warm'],
      ['wall_warm', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'wall_warm'],
      ['wall_warm', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'wall_warm'],
      ['wall_warm', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'wall_warm'],
      ['wall_warm', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'floor_carpet', 'wall_warm'],
      ['wall_warm', 'wall_warm', 'wall_warm', 'wall_warm', 'wall_warm', 'wall_warm', 'wall_warm', 'wall_warm', 'wall_warm', 'wall_warm', 'wall_warm', 'wall_warm', 'wall_warm', 'wall_warm', 'wall_warm', 'wall_warm'],
    ],
    decor: [
      ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
      ['', '', 'window', 'window', '', '', '', '', '', '', '', '', 'window', 'window', '', ''],
      ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
      ['', '', 'bookshelf', 'desk', 'chair', 'papers', '', '', '', '', 'board', 'archive', 'lamp', 'plant', '', ''],
      ['', '', '', '', 'plant', 'rug', 'table', 'chair', 'chair', 'lamp', '', '', '', '', '', ''],
      ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
      ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
      ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
      ['', '', '', '', 'bench', 'plant', 'papers', '', 'table', 'chair', 'rug', 'window', 'window', 'plant', '', ''],
      ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
      ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
      ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
    ],
    walkable: [
      [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      [false, true, false, false, true, true, true, true, true, true, true, true, false, false, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, true, false, false, false, false, true, true, true, true, false, false, false, false, true, false],
      [false, true, true, true, false, false, false, false, false, false, true, true, true, true, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, true, true, true, false, false, false, true, false, false, false, false, false, false, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    ],
    locations: {
      rinascita_scholar_hall: { x: 3, y: 4, label: '隐海修会书厅' },
      rinascita_laguna_forum: { x: 8, y: 5, label: '拉古那议事台' },
      rinascita_archive: { x: 11, y: 4, label: '潮汐档案库' },
      rinascita_tide_observatory: { x: 12, y: 7, label: '观潮台' },
      rinascita_cloister: { x: 4, y: 9, label: '回廊静室' },
      rinascita_center: { x: 8, y: 8, label: '城邦中庭' },
      rinascita_walk_1: { x: 6, y: 7, label: '拱廊 A' },
      rinascita_walk_2: { x: 10, y: 9, label: '拱廊 B' },
    },
  },
  frontier: {
    floor: [
      ['wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall'],
      ['wall', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'floor_grid', 'floor_grid', 'floor_grid', 'floor_grid', 'floor_grid', 'floor_blue', 'floor_blue', 'floor_blue', 'floor_blue', 'floor_blue', 'wall'],
      ['wall', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'floor_grid', 'floor_grid', 'floor_grid', 'floor_grid', 'floor_grid', 'floor_blue', 'floor_blue', 'floor_blue', 'floor_blue', 'floor_blue', 'wall'],
      ['wall', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'floor_grid', 'floor_grid', 'floor_grid', 'floor_grid', 'floor_grid', 'floor_blue', 'floor_blue', 'floor_blue', 'floor_blue', 'floor_blue', 'wall'],
      ['wall', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'floor_grid', 'floor_grid', 'floor_grid', 'floor_grid', 'floor_grid', 'floor_blue', 'floor_blue', 'floor_blue', 'floor_blue', 'floor_blue', 'wall'],
      ['wall', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'floor', 'floor', 'floor', 'floor', 'floor', 'floor_blue', 'floor_blue', 'floor_blue', 'floor_blue', 'floor_blue', 'wall'],
      ['wall', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'floor', 'floor', 'floor', 'floor', 'floor', 'floor_blue', 'floor_blue', 'floor_blue', 'floor_blue', 'floor_blue', 'wall'],
      ['wall', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'floor', 'floor', 'floor', 'floor', 'floor', 'floor_blue', 'floor_blue', 'floor_blue', 'floor_blue', 'floor_blue', 'wall'],
      ['wall', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_blue', 'floor_blue', 'floor_blue', 'floor_blue', 'floor_blue', 'wall'],
      ['wall', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_blue', 'floor_blue', 'floor_blue', 'floor_blue', 'floor_blue', 'wall'],
      ['wall', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank_dark', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_plank', 'floor_blue', 'floor_blue', 'floor_blue', 'floor_blue', 'floor_blue', 'wall'],
      ['wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall', 'wall'],
    ],
    decor: [
      ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
      ['', '', '', '', '', '', '', '', '', '', '', '', 'window', 'window', '', ''],
      ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
      ['', '', 'console', 'monitor', 'desk', 'chair', '', '', '', 'board', 'pillar', 'lamp', 'papers', '', '', ''],
      ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
      ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
      ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
      ['', '', '', '', 'crate', '', '', '', '', '', '', '', '', '', '', ''],
      ['', '', '', '', '', 'bar', 'chair', 'rug', 'crate', '', 'table', 'chair', 'bench', 'plant', '', ''],
      ['', '', '', '', '', '', '', '', '', '', '', '', 'papers', '', '', ''],
      ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
      ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
    ],
    walkable: [
      [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, false, false, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, true, false, false, false, false, true, true, true, false, false, false, false, true, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, true, true, true, false, true, true, true, true, true, true, true, true, true, true, false],
      [false, true, true, true, true, false, false, false, false, true, false, false, false, false, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, false, true, true, false],
      [false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false],
      [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false],
    ],
    locations: {
      frontier_command_post: { x: 3, y: 4, label: '北落野前哨' },
      frontier_horizon_scope: { x: 8, y: 4, label: '地平观测镜' },
      frontier_ruins_gate: { x: 11, y: 5, label: '稷廷遗址入口' },
      frontier_field_lab: { x: 5, y: 9, label: '野外实验台' },
      frontier_campfire: { x: 12, y: 9, label: '营火区' },
      frontier_center: { x: 8, y: 7, label: '风蚀平台' },
      frontier_walk_1: { x: 6, y: 6, label: '巡逻线 A' },
      frontier_walk_2: { x: 10, y: 8, label: '巡逻线 B' },
    },
  },
};
